// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ipban"
)

// IPBanCreate is the builder for creating a IPBan entity.
type IPBanCreate struct {
	config
	mutation *IPBanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IPBanCreate) SetCreatedAt(v time.Time) *IPBanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableCreatedAt(v *time.Time) *IPBanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IPBanCreate) SetUpdatedAt(v time.Time) *IPBanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableUpdatedAt(v *time.Time) *IPBanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *IPBanCreate) SetDeletedAt(v time.Time) *IPBanCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableDeletedAt(v *time.Time) *IPBanCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetRuleType sets the "rule_type" field.
func (_c *IPBanCreate) SetRuleType(v string) *IPBanCreate {
	_c.mutation.SetRuleType(v)
	return _c
}

// SetNillableRuleType sets the "rule_type" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableRuleType(v *string) *IPBanCreate {
	if v != nil {
		_c.SetRuleType(*v)
	}
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *IPBanCreate) SetPattern(v string) *IPBanCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetUaPattern sets the "ua_pattern" field.
func (_c *IPBanCreate) SetUaPattern(v string) *IPBanCreate {
	_c.mutation.SetUaPattern(v)
	return _c
}

// SetNillableUaPattern sets the "ua_pattern" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableUaPattern(v *string) *IPBanCreate {
	if v != nil {
		_c.SetUaPattern(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IPBanCreate) SetStatus(v string) *IPBanCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableStatus(v *string) *IPBanCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *IPBanCreate) SetReason(v string) *IPBanCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableReason(v *string) *IPBanCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *IPBanCreate) SetSource(v string) *IPBanCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableSource(v *string) *IPBanCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *IPBanCreate) SetCreatedBy(v int64) *IPBanCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableCreatedBy(v *int64) *IPBanCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *IPBanCreate) SetExpiresAt(v time.Time) *IPBanCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableExpiresAt(v *time.Time) *IPBanCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastHitAt sets the "last_hit_at" field.
func (_c *IPBanCreate) SetLastHitAt(v time.Time) *IPBanCreate {
	_c.mutation.SetLastHitAt(v)
	return _c
}

// SetNillableLastHitAt sets the "last_hit_at" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableLastHitAt(v *time.Time) *IPBanCreate {
	if v != nil {
		_c.SetLastHitAt(*v)
	}
	return _c
}

// SetHitCount sets the "hit_count" field.
func (_c *IPBanCreate) SetHitCount(v int64) *IPBanCreate {
	_c.mutation.SetHitCount(v)
	return _c
}

// SetNillableHitCount sets the "hit_count" field if the given value is not nil.
func (_c *IPBanCreate) SetNillableHitCount(v *int64) *IPBanCreate {
	if v != nil {
		_c.SetHitCount(*v)
	}
	return _c
}

// Mutation returns the IPBanMutation object of the builder.
func (_c *IPBanCreate) Mutation() *IPBanMutation {
	return _c.mutation
}

// Save creates the IPBan in the database.
func (_c *IPBanCreate) Save(ctx context.Context) (*IPBan, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IPBanCreate) SaveX(ctx context.Context) *IPBan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IPBanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IPBanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IPBanCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if ipban.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized ipban.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := ipban.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if ipban.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ipban.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ipban.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RuleType(); !ok {
		v := ipban.DefaultRuleType
		_c.mutation.SetRuleType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ipban.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := ipban.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.HitCount(); !ok {
		v := ipban.DefaultHitCount
		_c.mutation.SetHitCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *IPBanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IPBan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IPBan.updated_at"`)}
	}
	if _, ok := _c.mutation.RuleType(); !ok {
		return &ValidationError{Name: "rule_type", err: errors.New(`ent: missing required field "IPBan.rule_type"`)}
	}
	if v, ok := _c.mutation.RuleType(); ok {
		if err := ipban.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "IPBan.rule_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pattern(); !ok {
		return &ValidationError{Name: "pattern", err: errors.New(`ent: missing required field "IPBan.pattern"`)}
	}
	if v, ok := _c.mutation.Pattern(); ok {
		if err := ipban.PatternValidator(v); err != nil {
			return &ValidationError{Name: "pattern", err: fmt.Errorf(`ent: validator failed for field "IPBan.pattern": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UaPattern(); ok {
		if err := ipban.UaPatternValidator(v); err != nil {
			return &ValidationError{Name: "ua_pattern", err: fmt.Errorf(`ent: validator failed for field "IPBan.ua_pattern": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IPBan.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ipban.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IPBan.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := ipban.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "IPBan.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "IPBan.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := ipban.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "IPBan.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HitCount(); !ok {
		return &ValidationError{Name: "hit_count", err: errors.New(`ent: missing required field "IPBan.hit_count"`)}
	}
	return nil
}

func (_c *IPBanCreate) sqlSave(ctx context.Context) (*IPBan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IPBanCreate) createSpec() (*IPBan, *sqlgraph.CreateSpec) {
	var (
		_node = &IPBan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ipban.Table, sqlgraph.NewFieldSpec(ipban.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ipban.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ipban.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(ipban.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.RuleType(); ok {
		_spec.SetField(ipban.FieldRuleType, field.TypeString, value)
		_node.RuleType = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(ipban.FieldPattern, field.TypeString, value)
		_node.Pattern = value
	}
	if value, ok := _c.mutation.UaPattern(); ok {
		_spec.SetField(ipban.FieldUaPattern, field.TypeString, value)
		_node.UaPattern = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ipban.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(ipban.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(ipban.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(ipban.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(ipban.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastHitAt(); ok {
		_spec.SetField(ipban.FieldLastHitAt, field.TypeTime, value)
		_node.LastHitAt = &value
	}
	if value, ok := _c.mutation.HitCount(); ok {
		_spec.SetField(ipban.FieldHitCount, field.TypeInt64, value)
		_node.HitCount = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IPBan.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IPBanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IPBanCreate) OnConflict(opts ...sql.ConflictOption) *IPBanUpsertOne {
	_c.conflict = opts
	return &IPBanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IPBan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IPBanCreate) OnConflictColumns(columns ...string) *IPBanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IPBanUpsertOne{
		create: _c,
	}
}

type (
	// IPBanUpsertOne is the builder for "upsert"-ing
	//  one IPBan node.
	IPBanUpsertOne struct {
		create *IPBanCreate
	}

	// IPBanUpsert is the "OnConflict" setter.
	IPBanUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IPBanUpsert) SetUpdatedAt(v time.Time) *IPBanUpsert {
	u.Set(ipban.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateUpdatedAt() *IPBanUpsert {
	u.SetExcluded(ipban.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IPBanUpsert) SetDeletedAt(v time.Time) *IPBanUpsert {
	u.Set(ipban.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateDeletedAt() *IPBanUpsert {
	u.SetExcluded(ipban.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IPBanUpsert) ClearDeletedAt() *IPBanUpsert {
	u.SetNull(ipban.FieldDeletedAt)
	return u
}

// SetRuleType sets the "rule_type" field.
func (u *IPBanUpsert) SetRuleType(v string) *IPBanUpsert {
	u.Set(ipban.FieldRuleType, v)
	return u
}

// UpdateRuleType sets the "rule_type" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateRuleType() *IPBanUpsert {
	u.SetExcluded(ipban.FieldRuleType)
	return u
}

// SetPattern sets the "pattern" field.
func (u *IPBanUpsert) SetPattern(v string) *IPBanUpsert {
	u.Set(ipban.FieldPattern, v)
	return u
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *IPBanUpsert) UpdatePattern() *IPBanUpsert {
	u.SetExcluded(ipban.FieldPattern)
	return u
}

// SetUaPattern sets the "ua_pattern" field.
func (u *IPBanUpsert) SetUaPattern(v string) *IPBanUpsert {
	u.Set(ipban.FieldUaPattern, v)
	return u
}

// UpdateUaPattern sets the "ua_pattern" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateUaPattern() *IPBanUpsert {
	u.SetExcluded(ipban.FieldUaPattern)
	return u
}

// ClearUaPattern clears the value of the "ua_pattern" field.
func (u *IPBanUpsert) ClearUaPattern() *IPBanUpsert {
	u.SetNull(ipban.FieldUaPattern)
	return u
}

// SetStatus sets the "status" field.
func (u *IPBanUpsert) SetStatus(v string) *IPBanUpsert {
	u.Set(ipban.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateStatus() *IPBanUpsert {
	u.SetExcluded(ipban.FieldStatus)
	return u
}

// SetReason sets the "reason" field.
func (u *IPBanUpsert) SetReason(v string) *IPBanUpsert {
	u.Set(ipban.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateReason() *IPBanUpsert {
	u.SetExcluded(ipban.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *IPBanUpsert) ClearReason() *IPBanUpsert {
	u.SetNull(ipban.FieldReason)
	return u
}

// SetSource sets the "source" field.
func (u *IPBanUpsert) SetSource(v string) *IPBanUpsert {
	u.Set(ipban.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateSource() *IPBanUpsert {
	u.SetExcluded(ipban.FieldSource)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *IPBanUpsert) SetCreatedBy(v int64) *IPBanUpsert {
	u.Set(ipban.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateCreatedBy() *IPBanUpsert {
	u.SetExcluded(ipban.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *IPBanUpsert) AddCreatedBy(v int64) *IPBanUpsert {
	u.Add(ipban.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IPBanUpsert) ClearCreatedBy() *IPBanUpsert {
	u.SetNull(ipban.FieldCreatedBy)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *IPBanUpsert) SetExpiresAt(v time.Time) *IPBanUpsert {
	u.Set(ipban.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateExpiresAt() *IPBanUpsert {
	u.SetExcluded(ipban.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *IPBanUpsert) ClearExpiresAt() *IPBanUpsert {
	u.SetNull(ipban.FieldExpiresAt)
	return u
}

// SetLastHitAt sets the "last_hit_at" field.
func (u *IPBanUpsert) SetLastHitAt(v time.Time) *IPBanUpsert {
	u.Set(ipban.FieldLastHitAt, v)
	return u
}

// UpdateLastHitAt sets the "last_hit_at" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateLastHitAt() *IPBanUpsert {
	u.SetExcluded(ipban.FieldLastHitAt)
	return u
}

// ClearLastHitAt clears the value of the "last_hit_at" field.
func (u *IPBanUpsert) ClearLastHitAt() *IPBanUpsert {
	u.SetNull(ipban.FieldLastHitAt)
	return u
}

// SetHitCount sets the "hit_count" field.
func (u *IPBanUpsert) SetHitCount(v int64) *IPBanUpsert {
	u.Set(ipban.FieldHitCount, v)
	return u
}

// UpdateHitCount sets the "hit_count" field to the value that was provided on create.
func (u *IPBanUpsert) UpdateHitCount() *IPBanUpsert {
	u.SetExcluded(ipban.FieldHitCount)
	return u
}

// AddHitCount adds v to the "hit_count" field.
func (u *IPBanUpsert) AddHitCount(v int64) *IPBanUpsert {
	u.Add(ipban.FieldHitCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IPBan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IPBanUpsertOne) UpdateNewValues() *IPBanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ipban.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IPBan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IPBanUpsertOne) Ignore() *IPBanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IPBanUpsertOne) DoNothing() *IPBanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IPBanCreate.OnConflict
// documentation for more info.
func (u *IPBanUpsertOne) Update(set func(*IPBanUpsert)) *IPBanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IPBanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IPBanUpsertOne) SetUpdatedAt(v time.Time) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateUpdatedAt() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IPBanUpsertOne) SetDeletedAt(v time.Time) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateDeletedAt() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IPBanUpsertOne) ClearDeletedAt() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearDeletedAt()
	})
}

// SetRuleType sets the "rule_type" field.
func (u *IPBanUpsertOne) SetRuleType(v string) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetRuleType(v)
	})
}

// UpdateRuleType sets the "rule_type" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateRuleType() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateRuleType()
	})
}

// SetPattern sets the "pattern" field.
func (u *IPBanUpsertOne) SetPattern(v string) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdatePattern() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdatePattern()
	})
}

// SetUaPattern sets the "ua_pattern" field.
func (u *IPBanUpsertOne) SetUaPattern(v string) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetUaPattern(v)
	})
}

// UpdateUaPattern sets the "ua_pattern" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateUaPattern() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateUaPattern()
	})
}

// ClearUaPattern clears the value of the "ua_pattern" field.
func (u *IPBanUpsertOne) ClearUaPattern() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearUaPattern()
	})
}

// SetStatus sets the "status" field.
func (u *IPBanUpsertOne) SetStatus(v string) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateStatus() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *IPBanUpsertOne) SetReason(v string) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateReason() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *IPBanUpsertOne) ClearReason() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearReason()
	})
}

// SetSource sets the "source" field.
func (u *IPBanUpsertOne) SetSource(v string) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateSource() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateSource()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *IPBanUpsertOne) SetCreatedBy(v int64) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *IPBanUpsertOne) AddCreatedBy(v int64) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateCreatedBy() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IPBanUpsertOne) ClearCreatedBy() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearCreatedBy()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *IPBanUpsertOne) SetExpiresAt(v time.Time) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateExpiresAt() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *IPBanUpsertOne) ClearExpiresAt() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastHitAt sets the "last_hit_at" field.
func (u *IPBanUpsertOne) SetLastHitAt(v time.Time) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetLastHitAt(v)
	})
}

// UpdateLastHitAt sets the "last_hit_at" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateLastHitAt() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateLastHitAt()
	})
}

// ClearLastHitAt clears the value of the "last_hit_at" field.
func (u *IPBanUpsertOne) ClearLastHitAt() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearLastHitAt()
	})
}

// SetHitCount sets the "hit_count" field.
func (u *IPBanUpsertOne) SetHitCount(v int64) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.SetHitCount(v)
	})
}

// AddHitCount adds v to the "hit_count" field.
func (u *IPBanUpsertOne) AddHitCount(v int64) *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.AddHitCount(v)
	})
}

// UpdateHitCount sets the "hit_count" field to the value that was provided on create.
func (u *IPBanUpsertOne) UpdateHitCount() *IPBanUpsertOne {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateHitCount()
	})
}

// Exec executes the query.
func (u *IPBanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IPBanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IPBanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IPBanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IPBanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IPBanCreateBulk is the builder for creating many IPBan entities in bulk.
type IPBanCreateBulk struct {
	config
	err      error
	builders []*IPBanCreate
	conflict []sql.ConflictOption
}

// Save creates the IPBan entities in the database.
func (_c *IPBanCreateBulk) Save(ctx context.Context) ([]*IPBan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IPBan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IPBanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IPBanCreateBulk) SaveX(ctx context.Context) []*IPBan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IPBanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IPBanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IPBan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IPBanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IPBanCreateBulk) OnConflict(opts ...sql.ConflictOption) *IPBanUpsertBulk {
	_c.conflict = opts
	return &IPBanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IPBan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IPBanCreateBulk) OnConflictColumns(columns ...string) *IPBanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IPBanUpsertBulk{
		create: _c,
	}
}

// IPBanUpsertBulk is the builder for "upsert"-ing
// a bulk of IPBan nodes.
type IPBanUpsertBulk struct {
	create *IPBanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IPBan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IPBanUpsertBulk) UpdateNewValues() *IPBanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ipban.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IPBan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IPBanUpsertBulk) Ignore() *IPBanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IPBanUpsertBulk) DoNothing() *IPBanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IPBanCreateBulk.OnConflict
// documentation for more info.
func (u *IPBanUpsertBulk) Update(set func(*IPBanUpsert)) *IPBanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IPBanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IPBanUpsertBulk) SetUpdatedAt(v time.Time) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateUpdatedAt() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IPBanUpsertBulk) SetDeletedAt(v time.Time) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateDeletedAt() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IPBanUpsertBulk) ClearDeletedAt() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearDeletedAt()
	})
}

// SetRuleType sets the "rule_type" field.
func (u *IPBanUpsertBulk) SetRuleType(v string) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetRuleType(v)
	})
}

// UpdateRuleType sets the "rule_type" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateRuleType() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateRuleType()
	})
}

// SetPattern sets the "pattern" field.
func (u *IPBanUpsertBulk) SetPattern(v string) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdatePattern() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdatePattern()
	})
}

// SetUaPattern sets the "ua_pattern" field.
func (u *IPBanUpsertBulk) SetUaPattern(v string) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetUaPattern(v)
	})
}

// UpdateUaPattern sets the "ua_pattern" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateUaPattern() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateUaPattern()
	})
}

// ClearUaPattern clears the value of the "ua_pattern" field.
func (u *IPBanUpsertBulk) ClearUaPattern() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearUaPattern()
	})
}

// SetStatus sets the "status" field.
func (u *IPBanUpsertBulk) SetStatus(v string) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateStatus() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *IPBanUpsertBulk) SetReason(v string) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateReason() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *IPBanUpsertBulk) ClearReason() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearReason()
	})
}

// SetSource sets the "source" field.
func (u *IPBanUpsertBulk) SetSource(v string) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateSource() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateSource()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *IPBanUpsertBulk) SetCreatedBy(v int64) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *IPBanUpsertBulk) AddCreatedBy(v int64) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateCreatedBy() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IPBanUpsertBulk) ClearCreatedBy() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearCreatedBy()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *IPBanUpsertBulk) SetExpiresAt(v time.Time) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateExpiresAt() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *IPBanUpsertBulk) ClearExpiresAt() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastHitAt sets the "last_hit_at" field.
func (u *IPBanUpsertBulk) SetLastHitAt(v time.Time) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetLastHitAt(v)
	})
}

// UpdateLastHitAt sets the "last_hit_at" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateLastHitAt() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateLastHitAt()
	})
}

// ClearLastHitAt clears the value of the "last_hit_at" field.
func (u *IPBanUpsertBulk) ClearLastHitAt() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.ClearLastHitAt()
	})
}

// SetHitCount sets the "hit_count" field.
func (u *IPBanUpsertBulk) SetHitCount(v int64) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.SetHitCount(v)
	})
}

// AddHitCount adds v to the "hit_count" field.
func (u *IPBanUpsertBulk) AddHitCount(v int64) *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.AddHitCount(v)
	})
}

// UpdateHitCount sets the "hit_count" field to the value that was provided on create.
func (u *IPBanUpsertBulk) UpdateHitCount() *IPBanUpsertBulk {
	return u.Update(func(s *IPBanUpsert) {
		s.UpdateHitCount()
	})
}

// Exec executes the query.
func (u *IPBanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IPBanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IPBanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IPBanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
