// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ipban"
)

// IPBan is the model entity for the IPBan schema.
type IPBan struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// ip/ua/ip_ua/email_suffix/email_regex
	RuleType string `json:"rule_type,omitempty"`
	// Primary match pattern
	Pattern string `json:"pattern,omitempty"`
	// UA pattern for ip_ua rules
	UaPattern *string `json:"ua_pattern,omitempty"`
	// active/inactive
	Status string `json:"status,omitempty"`
	// Ban reason
	Reason *string `json:"reason,omitempty"`
	// Ban source
	Source string `json:"source,omitempty"`
	// Admin user id that created the ban
	CreatedBy *int64 `json:"created_by,omitempty"`
	// Expiration time; null means permanent
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Last time this rule blocked a request
	LastHitAt *time.Time `json:"last_hit_at,omitempty"`
	// Number of blocked requests
	HitCount     int64 `json:"hit_count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IPBan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ipban.FieldID, ipban.FieldCreatedBy, ipban.FieldHitCount:
			values[i] = new(sql.NullInt64)
		case ipban.FieldRuleType, ipban.FieldPattern, ipban.FieldUaPattern, ipban.FieldStatus, ipban.FieldReason, ipban.FieldSource:
			values[i] = new(sql.NullString)
		case ipban.FieldCreatedAt, ipban.FieldUpdatedAt, ipban.FieldDeletedAt, ipban.FieldExpiresAt, ipban.FieldLastHitAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IPBan fields.
func (_m *IPBan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ipban.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ipban.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ipban.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ipban.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case ipban.FieldRuleType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_type", values[i])
			} else if value.Valid {
				_m.RuleType = value.String
			}
		case ipban.FieldPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pattern", values[i])
			} else if value.Valid {
				_m.Pattern = value.String
			}
		case ipban.FieldUaPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ua_pattern", values[i])
			} else if value.Valid {
				_m.UaPattern = new(string)
				*_m.UaPattern = value.String
			}
		case ipban.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ipban.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case ipban.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case ipban.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case ipban.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case ipban.FieldLastHitAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_hit_at", values[i])
			} else if value.Valid {
				_m.LastHitAt = new(time.Time)
				*_m.LastHitAt = value.Time
			}
		case ipban.FieldHitCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hit_count", values[i])
			} else if value.Valid {
				_m.HitCount = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IPBan.
// This includes values selected through modifiers, order, etc.
func (_m *IPBan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IPBan.
// Note that you need to call IPBan.Unwrap() before calling this method if this IPBan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IPBan) Update() *IPBanUpdateOne {
	return NewIPBanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IPBan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IPBan) Unwrap() *IPBan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IPBan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IPBan) String() string {
	var builder strings.Builder
	builder.WriteString("IPBan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("rule_type=")
	builder.WriteString(_m.RuleType)
	builder.WriteString(", ")
	builder.WriteString("pattern=")
	builder.WriteString(_m.Pattern)
	builder.WriteString(", ")
	if v := _m.UaPattern; v != nil {
		builder.WriteString("ua_pattern=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastHitAt; v != nil {
		builder.WriteString("last_hit_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("hit_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.HitCount))
	builder.WriteByte(')')
	return builder.String()
}

// IPBans is a parsable slice of IPBan.
type IPBans []*IPBan
