// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ipban"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IPBanUpdate is the builder for updating IPBan entities.
type IPBanUpdate struct {
	config
	hooks    []Hook
	mutation *IPBanMutation
}

// Where appends a list predicates to the IPBanUpdate builder.
func (_u *IPBanUpdate) Where(ps ...predicate.IPBan) *IPBanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IPBanUpdate) SetUpdatedAt(v time.Time) *IPBanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IPBanUpdate) SetDeletedAt(v time.Time) *IPBanUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableDeletedAt(v *time.Time) *IPBanUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *IPBanUpdate) ClearDeletedAt() *IPBanUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRuleType sets the "rule_type" field.
func (_u *IPBanUpdate) SetRuleType(v string) *IPBanUpdate {
	_u.mutation.SetRuleType(v)
	return _u
}

// SetNillableRuleType sets the "rule_type" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableRuleType(v *string) *IPBanUpdate {
	if v != nil {
		_u.SetRuleType(*v)
	}
	return _u
}

// SetPattern sets the "pattern" field.
func (_u *IPBanUpdate) SetPattern(v string) *IPBanUpdate {
	_u.mutation.SetPattern(v)
	return _u
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillablePattern(v *string) *IPBanUpdate {
	if v != nil {
		_u.SetPattern(*v)
	}
	return _u
}

// SetUaPattern sets the "ua_pattern" field.
func (_u *IPBanUpdate) SetUaPattern(v string) *IPBanUpdate {
	_u.mutation.SetUaPattern(v)
	return _u
}

// SetNillableUaPattern sets the "ua_pattern" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableUaPattern(v *string) *IPBanUpdate {
	if v != nil {
		_u.SetUaPattern(*v)
	}
	return _u
}

// ClearUaPattern clears the value of the "ua_pattern" field.
func (_u *IPBanUpdate) ClearUaPattern() *IPBanUpdate {
	_u.mutation.ClearUaPattern()
	return _u
}

// SetStatus sets the "status" field.
func (_u *IPBanUpdate) SetStatus(v string) *IPBanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableStatus(v *string) *IPBanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *IPBanUpdate) SetReason(v string) *IPBanUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableReason(v *string) *IPBanUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *IPBanUpdate) ClearReason() *IPBanUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetSource sets the "source" field.
func (_u *IPBanUpdate) SetSource(v string) *IPBanUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableSource(v *string) *IPBanUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *IPBanUpdate) SetCreatedBy(v int64) *IPBanUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableCreatedBy(v *int64) *IPBanUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *IPBanUpdate) AddCreatedBy(v int64) *IPBanUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *IPBanUpdate) ClearCreatedBy() *IPBanUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IPBanUpdate) SetExpiresAt(v time.Time) *IPBanUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableExpiresAt(v *time.Time) *IPBanUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *IPBanUpdate) ClearExpiresAt() *IPBanUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastHitAt sets the "last_hit_at" field.
func (_u *IPBanUpdate) SetLastHitAt(v time.Time) *IPBanUpdate {
	_u.mutation.SetLastHitAt(v)
	return _u
}

// SetNillableLastHitAt sets the "last_hit_at" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableLastHitAt(v *time.Time) *IPBanUpdate {
	if v != nil {
		_u.SetLastHitAt(*v)
	}
	return _u
}

// ClearLastHitAt clears the value of the "last_hit_at" field.
func (_u *IPBanUpdate) ClearLastHitAt() *IPBanUpdate {
	_u.mutation.ClearLastHitAt()
	return _u
}

// SetHitCount sets the "hit_count" field.
func (_u *IPBanUpdate) SetHitCount(v int64) *IPBanUpdate {
	_u.mutation.ResetHitCount()
	_u.mutation.SetHitCount(v)
	return _u
}

// SetNillableHitCount sets the "hit_count" field if the given value is not nil.
func (_u *IPBanUpdate) SetNillableHitCount(v *int64) *IPBanUpdate {
	if v != nil {
		_u.SetHitCount(*v)
	}
	return _u
}

// AddHitCount adds value to the "hit_count" field.
func (_u *IPBanUpdate) AddHitCount(v int64) *IPBanUpdate {
	_u.mutation.AddHitCount(v)
	return _u
}

// Mutation returns the IPBanMutation object of the builder.
func (_u *IPBanUpdate) Mutation() *IPBanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IPBanUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IPBanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IPBanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IPBanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IPBanUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ipban.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ipban.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ipban.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *IPBanUpdate) check() error {
	if v, ok := _u.mutation.RuleType(); ok {
		if err := ipban.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "IPBan.rule_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pattern(); ok {
		if err := ipban.PatternValidator(v); err != nil {
			return &ValidationError{Name: "pattern", err: fmt.Errorf(`ent: validator failed for field "IPBan.pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UaPattern(); ok {
		if err := ipban.UaPatternValidator(v); err != nil {
			return &ValidationError{Name: "ua_pattern", err: fmt.Errorf(`ent: validator failed for field "IPBan.ua_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ipban.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IPBan.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := ipban.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "IPBan.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := ipban.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "IPBan.source": %w`, err)}
		}
	}
	return nil
}

func (_u *IPBanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ipban.Table, ipban.Columns, sqlgraph.NewFieldSpec(ipban.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ipban.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ipban.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ipban.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RuleType(); ok {
		_spec.SetField(ipban.FieldRuleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pattern(); ok {
		_spec.SetField(ipban.FieldPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.UaPattern(); ok {
		_spec.SetField(ipban.FieldUaPattern, field.TypeString, value)
	}
	if _u.mutation.UaPatternCleared() {
		_spec.ClearField(ipban.FieldUaPattern, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ipban.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(ipban.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(ipban.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(ipban.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(ipban.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(ipban.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(ipban.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(ipban.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(ipban.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastHitAt(); ok {
		_spec.SetField(ipban.FieldLastHitAt, field.TypeTime, value)
	}
	if _u.mutation.LastHitAtCleared() {
		_spec.ClearField(ipban.FieldLastHitAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HitCount(); ok {
		_spec.SetField(ipban.FieldHitCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHitCount(); ok {
		_spec.AddField(ipban.FieldHitCount, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ipban.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IPBanUpdateOne is the builder for updating a single IPBan entity.
type IPBanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IPBanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IPBanUpdateOne) SetUpdatedAt(v time.Time) *IPBanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IPBanUpdateOne) SetDeletedAt(v time.Time) *IPBanUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableDeletedAt(v *time.Time) *IPBanUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *IPBanUpdateOne) ClearDeletedAt() *IPBanUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRuleType sets the "rule_type" field.
func (_u *IPBanUpdateOne) SetRuleType(v string) *IPBanUpdateOne {
	_u.mutation.SetRuleType(v)
	return _u
}

// SetNillableRuleType sets the "rule_type" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableRuleType(v *string) *IPBanUpdateOne {
	if v != nil {
		_u.SetRuleType(*v)
	}
	return _u
}

// SetPattern sets the "pattern" field.
func (_u *IPBanUpdateOne) SetPattern(v string) *IPBanUpdateOne {
	_u.mutation.SetPattern(v)
	return _u
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillablePattern(v *string) *IPBanUpdateOne {
	if v != nil {
		_u.SetPattern(*v)
	}
	return _u
}

// SetUaPattern sets the "ua_pattern" field.
func (_u *IPBanUpdateOne) SetUaPattern(v string) *IPBanUpdateOne {
	_u.mutation.SetUaPattern(v)
	return _u
}

// SetNillableUaPattern sets the "ua_pattern" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableUaPattern(v *string) *IPBanUpdateOne {
	if v != nil {
		_u.SetUaPattern(*v)
	}
	return _u
}

// ClearUaPattern clears the value of the "ua_pattern" field.
func (_u *IPBanUpdateOne) ClearUaPattern() *IPBanUpdateOne {
	_u.mutation.ClearUaPattern()
	return _u
}

// SetStatus sets the "status" field.
func (_u *IPBanUpdateOne) SetStatus(v string) *IPBanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableStatus(v *string) *IPBanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *IPBanUpdateOne) SetReason(v string) *IPBanUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableReason(v *string) *IPBanUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *IPBanUpdateOne) ClearReason() *IPBanUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetSource sets the "source" field.
func (_u *IPBanUpdateOne) SetSource(v string) *IPBanUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableSource(v *string) *IPBanUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *IPBanUpdateOne) SetCreatedBy(v int64) *IPBanUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableCreatedBy(v *int64) *IPBanUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *IPBanUpdateOne) AddCreatedBy(v int64) *IPBanUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *IPBanUpdateOne) ClearCreatedBy() *IPBanUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IPBanUpdateOne) SetExpiresAt(v time.Time) *IPBanUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableExpiresAt(v *time.Time) *IPBanUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *IPBanUpdateOne) ClearExpiresAt() *IPBanUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastHitAt sets the "last_hit_at" field.
func (_u *IPBanUpdateOne) SetLastHitAt(v time.Time) *IPBanUpdateOne {
	_u.mutation.SetLastHitAt(v)
	return _u
}

// SetNillableLastHitAt sets the "last_hit_at" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableLastHitAt(v *time.Time) *IPBanUpdateOne {
	if v != nil {
		_u.SetLastHitAt(*v)
	}
	return _u
}

// ClearLastHitAt clears the value of the "last_hit_at" field.
func (_u *IPBanUpdateOne) ClearLastHitAt() *IPBanUpdateOne {
	_u.mutation.ClearLastHitAt()
	return _u
}

// SetHitCount sets the "hit_count" field.
func (_u *IPBanUpdateOne) SetHitCount(v int64) *IPBanUpdateOne {
	_u.mutation.ResetHitCount()
	_u.mutation.SetHitCount(v)
	return _u
}

// SetNillableHitCount sets the "hit_count" field if the given value is not nil.
func (_u *IPBanUpdateOne) SetNillableHitCount(v *int64) *IPBanUpdateOne {
	if v != nil {
		_u.SetHitCount(*v)
	}
	return _u
}

// AddHitCount adds value to the "hit_count" field.
func (_u *IPBanUpdateOne) AddHitCount(v int64) *IPBanUpdateOne {
	_u.mutation.AddHitCount(v)
	return _u
}

// Mutation returns the IPBanMutation object of the builder.
func (_u *IPBanUpdateOne) Mutation() *IPBanMutation {
	return _u.mutation
}

// Where appends a list predicates to the IPBanUpdate builder.
func (_u *IPBanUpdateOne) Where(ps ...predicate.IPBan) *IPBanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IPBanUpdateOne) Select(field string, fields ...string) *IPBanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IPBan entity.
func (_u *IPBanUpdateOne) Save(ctx context.Context) (*IPBan, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IPBanUpdateOne) SaveX(ctx context.Context) *IPBan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IPBanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IPBanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IPBanUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ipban.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ipban.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ipban.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *IPBanUpdateOne) check() error {
	if v, ok := _u.mutation.RuleType(); ok {
		if err := ipban.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "IPBan.rule_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pattern(); ok {
		if err := ipban.PatternValidator(v); err != nil {
			return &ValidationError{Name: "pattern", err: fmt.Errorf(`ent: validator failed for field "IPBan.pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UaPattern(); ok {
		if err := ipban.UaPatternValidator(v); err != nil {
			return &ValidationError{Name: "ua_pattern", err: fmt.Errorf(`ent: validator failed for field "IPBan.ua_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ipban.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IPBan.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := ipban.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "IPBan.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := ipban.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "IPBan.source": %w`, err)}
		}
	}
	return nil
}

func (_u *IPBanUpdateOne) sqlSave(ctx context.Context) (_node *IPBan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ipban.Table, ipban.Columns, sqlgraph.NewFieldSpec(ipban.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IPBan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ipban.FieldID)
		for _, f := range fields {
			if !ipban.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ipban.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ipban.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ipban.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ipban.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RuleType(); ok {
		_spec.SetField(ipban.FieldRuleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pattern(); ok {
		_spec.SetField(ipban.FieldPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.UaPattern(); ok {
		_spec.SetField(ipban.FieldUaPattern, field.TypeString, value)
	}
	if _u.mutation.UaPatternCleared() {
		_spec.ClearField(ipban.FieldUaPattern, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ipban.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(ipban.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(ipban.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(ipban.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(ipban.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(ipban.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(ipban.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(ipban.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(ipban.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastHitAt(); ok {
		_spec.SetField(ipban.FieldLastHitAt, field.TypeTime, value)
	}
	if _u.mutation.LastHitAtCleared() {
		_spec.ClearField(ipban.FieldLastHitAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HitCount(); ok {
		_spec.SetField(ipban.FieldHitCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHitCount(); ok {
		_spec.AddField(ipban.FieldHitCount, field.TypeInt64, value)
	}
	_node = &IPBan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ipban.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
