// Code generated by ent, DO NOT EDIT.

package ipban

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ipban type in the database.
	Label = "ip_ban"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldRuleType holds the string denoting the rule_type field in the database.
	FieldRuleType = "rule_type"
	// FieldPattern holds the string denoting the pattern field in the database.
	FieldPattern = "pattern"
	// FieldUaPattern holds the string denoting the ua_pattern field in the database.
	FieldUaPattern = "ua_pattern"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldLastHitAt holds the string denoting the last_hit_at field in the database.
	FieldLastHitAt = "last_hit_at"
	// FieldHitCount holds the string denoting the hit_count field in the database.
	FieldHitCount = "hit_count"
	// Table holds the table name of the ipban in the database.
	Table = "ip_bans"
)

// Columns holds all SQL columns for ipban fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldRuleType,
	FieldPattern,
	FieldUaPattern,
	FieldStatus,
	FieldReason,
	FieldSource,
	FieldCreatedBy,
	FieldExpiresAt,
	FieldLastHitAt,
	FieldHitCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultRuleType holds the default value on creation for the "rule_type" field.
	DefaultRuleType string
	// RuleTypeValidator is a validator for the "rule_type" field. It is called by the builders before save.
	RuleTypeValidator func(string) error
	// PatternValidator is a validator for the "pattern" field. It is called by the builders before save.
	PatternValidator func(string) error
	// UaPatternValidator is a validator for the "ua_pattern" field. It is called by the builders before save.
	UaPatternValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultHitCount holds the default value on creation for the "hit_count" field.
	DefaultHitCount int64
)

// OrderOption defines the ordering options for the IPBan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByRuleType orders the results by the rule_type field.
func ByRuleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleType, opts...).ToFunc()
}

// ByPattern orders the results by the pattern field.
func ByPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPattern, opts...).ToFunc()
}

// ByUaPattern orders the results by the ua_pattern field.
func ByUaPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUaPattern, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByLastHitAt orders the results by the last_hit_at field.
func ByLastHitAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastHitAt, opts...).ToFunc()
}

// ByHitCount orders the results by the hit_count field.
func ByHitCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHitCount, opts...).ToFunc()
}
