// Code generated by ent, DO NOT EDIT.

package ipban

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldDeletedAt, v))
}

// RuleType applies equality check predicate on the "rule_type" field. It's identical to RuleTypeEQ.
func RuleType(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldRuleType, v))
}

// Pattern applies equality check predicate on the "pattern" field. It's identical to PatternEQ.
func Pattern(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldPattern, v))
}

// UaPattern applies equality check predicate on the "ua_pattern" field. It's identical to UaPatternEQ.
func UaPattern(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldUaPattern, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldStatus, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldReason, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldSource, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldCreatedBy, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldExpiresAt, v))
}

// LastHitAt applies equality check predicate on the "last_hit_at" field. It's identical to LastHitAtEQ.
func LastHitAt(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldLastHitAt, v))
}

// HitCount applies equality check predicate on the "hit_count" field. It's identical to HitCountEQ.
func HitCount(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldHitCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldNotNull(FieldDeletedAt))
}

// RuleTypeEQ applies the EQ predicate on the "rule_type" field.
func RuleTypeEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldRuleType, v))
}

// RuleTypeNEQ applies the NEQ predicate on the "rule_type" field.
func RuleTypeNEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldRuleType, v))
}

// RuleTypeIn applies the In predicate on the "rule_type" field.
func RuleTypeIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldRuleType, vs...))
}

// RuleTypeNotIn applies the NotIn predicate on the "rule_type" field.
func RuleTypeNotIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldRuleType, vs...))
}

// RuleTypeGT applies the GT predicate on the "rule_type" field.
func RuleTypeGT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldRuleType, v))
}

// RuleTypeGTE applies the GTE predicate on the "rule_type" field.
func RuleTypeGTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldRuleType, v))
}

// RuleTypeLT applies the LT predicate on the "rule_type" field.
func RuleTypeLT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldRuleType, v))
}

// RuleTypeLTE applies the LTE predicate on the "rule_type" field.
func RuleTypeLTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldRuleType, v))
}

// RuleTypeContains applies the Contains predicate on the "rule_type" field.
func RuleTypeContains(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContains(FieldRuleType, v))
}

// RuleTypeHasPrefix applies the HasPrefix predicate on the "rule_type" field.
func RuleTypeHasPrefix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasPrefix(FieldRuleType, v))
}

// RuleTypeHasSuffix applies the HasSuffix predicate on the "rule_type" field.
func RuleTypeHasSuffix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasSuffix(FieldRuleType, v))
}

// RuleTypeEqualFold applies the EqualFold predicate on the "rule_type" field.
func RuleTypeEqualFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEqualFold(FieldRuleType, v))
}

// RuleTypeContainsFold applies the ContainsFold predicate on the "rule_type" field.
func RuleTypeContainsFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContainsFold(FieldRuleType, v))
}

// PatternEQ applies the EQ predicate on the "pattern" field.
func PatternEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldPattern, v))
}

// PatternNEQ applies the NEQ predicate on the "pattern" field.
func PatternNEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldPattern, v))
}

// PatternIn applies the In predicate on the "pattern" field.
func PatternIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldPattern, vs...))
}

// PatternNotIn applies the NotIn predicate on the "pattern" field.
func PatternNotIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldPattern, vs...))
}

// PatternGT applies the GT predicate on the "pattern" field.
func PatternGT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldPattern, v))
}

// PatternGTE applies the GTE predicate on the "pattern" field.
func PatternGTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldPattern, v))
}

// PatternLT applies the LT predicate on the "pattern" field.
func PatternLT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldPattern, v))
}

// PatternLTE applies the LTE predicate on the "pattern" field.
func PatternLTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldPattern, v))
}

// PatternContains applies the Contains predicate on the "pattern" field.
func PatternContains(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContains(FieldPattern, v))
}

// PatternHasPrefix applies the HasPrefix predicate on the "pattern" field.
func PatternHasPrefix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasPrefix(FieldPattern, v))
}

// PatternHasSuffix applies the HasSuffix predicate on the "pattern" field.
func PatternHasSuffix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasSuffix(FieldPattern, v))
}

// PatternEqualFold applies the EqualFold predicate on the "pattern" field.
func PatternEqualFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEqualFold(FieldPattern, v))
}

// PatternContainsFold applies the ContainsFold predicate on the "pattern" field.
func PatternContainsFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContainsFold(FieldPattern, v))
}

// UaPatternEQ applies the EQ predicate on the "ua_pattern" field.
func UaPatternEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldUaPattern, v))
}

// UaPatternNEQ applies the NEQ predicate on the "ua_pattern" field.
func UaPatternNEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldUaPattern, v))
}

// UaPatternIn applies the In predicate on the "ua_pattern" field.
func UaPatternIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldUaPattern, vs...))
}

// UaPatternNotIn applies the NotIn predicate on the "ua_pattern" field.
func UaPatternNotIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldUaPattern, vs...))
}

// UaPatternGT applies the GT predicate on the "ua_pattern" field.
func UaPatternGT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldUaPattern, v))
}

// UaPatternGTE applies the GTE predicate on the "ua_pattern" field.
func UaPatternGTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldUaPattern, v))
}

// UaPatternLT applies the LT predicate on the "ua_pattern" field.
func UaPatternLT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldUaPattern, v))
}

// UaPatternLTE applies the LTE predicate on the "ua_pattern" field.
func UaPatternLTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldUaPattern, v))
}

// UaPatternContains applies the Contains predicate on the "ua_pattern" field.
func UaPatternContains(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContains(FieldUaPattern, v))
}

// UaPatternHasPrefix applies the HasPrefix predicate on the "ua_pattern" field.
func UaPatternHasPrefix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasPrefix(FieldUaPattern, v))
}

// UaPatternHasSuffix applies the HasSuffix predicate on the "ua_pattern" field.
func UaPatternHasSuffix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasSuffix(FieldUaPattern, v))
}

// UaPatternIsNil applies the IsNil predicate on the "ua_pattern" field.
func UaPatternIsNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldIsNull(FieldUaPattern))
}

// UaPatternNotNil applies the NotNil predicate on the "ua_pattern" field.
func UaPatternNotNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldNotNull(FieldUaPattern))
}

// UaPatternEqualFold applies the EqualFold predicate on the "ua_pattern" field.
func UaPatternEqualFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEqualFold(FieldUaPattern, v))
}

// UaPatternContainsFold applies the ContainsFold predicate on the "ua_pattern" field.
func UaPatternContainsFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContainsFold(FieldUaPattern, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContainsFold(FieldStatus, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContainsFold(FieldReason, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.IPBan {
	return predicate.IPBan(sql.FieldContainsFold(FieldSource, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldNotNull(FieldCreatedBy))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldNotNull(FieldExpiresAt))
}

// LastHitAtEQ applies the EQ predicate on the "last_hit_at" field.
func LastHitAtEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldLastHitAt, v))
}

// LastHitAtNEQ applies the NEQ predicate on the "last_hit_at" field.
func LastHitAtNEQ(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldLastHitAt, v))
}

// LastHitAtIn applies the In predicate on the "last_hit_at" field.
func LastHitAtIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldLastHitAt, vs...))
}

// LastHitAtNotIn applies the NotIn predicate on the "last_hit_at" field.
func LastHitAtNotIn(vs ...time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldLastHitAt, vs...))
}

// LastHitAtGT applies the GT predicate on the "last_hit_at" field.
func LastHitAtGT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldLastHitAt, v))
}

// LastHitAtGTE applies the GTE predicate on the "last_hit_at" field.
func LastHitAtGTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldLastHitAt, v))
}

// LastHitAtLT applies the LT predicate on the "last_hit_at" field.
func LastHitAtLT(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldLastHitAt, v))
}

// LastHitAtLTE applies the LTE predicate on the "last_hit_at" field.
func LastHitAtLTE(v time.Time) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldLastHitAt, v))
}

// LastHitAtIsNil applies the IsNil predicate on the "last_hit_at" field.
func LastHitAtIsNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldIsNull(FieldLastHitAt))
}

// LastHitAtNotNil applies the NotNil predicate on the "last_hit_at" field.
func LastHitAtNotNil() predicate.IPBan {
	return predicate.IPBan(sql.FieldNotNull(FieldLastHitAt))
}

// HitCountEQ applies the EQ predicate on the "hit_count" field.
func HitCountEQ(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldEQ(FieldHitCount, v))
}

// HitCountNEQ applies the NEQ predicate on the "hit_count" field.
func HitCountNEQ(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldNEQ(FieldHitCount, v))
}

// HitCountIn applies the In predicate on the "hit_count" field.
func HitCountIn(vs ...int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldIn(FieldHitCount, vs...))
}

// HitCountNotIn applies the NotIn predicate on the "hit_count" field.
func HitCountNotIn(vs ...int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldNotIn(FieldHitCount, vs...))
}

// HitCountGT applies the GT predicate on the "hit_count" field.
func HitCountGT(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldGT(FieldHitCount, v))
}

// HitCountGTE applies the GTE predicate on the "hit_count" field.
func HitCountGTE(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldGTE(FieldHitCount, v))
}

// HitCountLT applies the LT predicate on the "hit_count" field.
func HitCountLT(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldLT(FieldHitCount, v))
}

// HitCountLTE applies the LTE predicate on the "hit_count" field.
func HitCountLTE(v int64) predicate.IPBan {
	return predicate.IPBan(sql.FieldLTE(FieldHitCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IPBan) predicate.IPBan {
	return predicate.IPBan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IPBan) predicate.IPBan {
	return predicate.IPBan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IPBan) predicate.IPBan {
	return predicate.IPBan(sql.NotPredicates(p))
}
